### Send POST request with json body
POST http://localhost:8080/set
Content-Type: application/json

{
  "key": "ozon",
  "value": "route256"
}

### Send GET request key exists
GET http://localhost:8080/get?key=ozon


### Send GET request key not exists
GET http://localhost:8080/get?key=route256